environment:
  VisualStudioVersion: 11.0

# TODO: add x64, fix issue: LNK1158: cannot run 'cvtres.exe'
platform:
  - Win32

# TODO: add VSDebug
configuration:
  - Release

install:
  - cmd: git clone https://github.com/libyal/libyal

before_build:
  - ps: .\synclibs.ps1
  - ps: .\autogen.ps1
  - cmd: C:\Python27\python.exe libyal\msvscpp-convert.py --to 2010 msvscpp\libfole.sln

build:
  project: vs2010\libfole.sln

